Vamos agora falar um pouco sobre matrizes. Em geral as matrizes são consideradas quase como a coluna dorsal de muitos problemas, então é interessante nos destrincharmos um pouco sobre elas. Inicialmente, podemos nos lembram de uma matriz de rotação de base. Se tivermos um ponto $\mathbf{r}=(x,y)^T$ e quisermos rotaciona-lo por um angulho $\theta$, podemos fazer isso da seguinte forma:
$$
\begin{bmatrix}
cos \theta & -sin \theta \\
sin \theta & cos \theta
\end{bmatrix}
\begin{bmatrix}
x \\
y
\end{bmatrix}
=
\begin{bmatrix}
x' \\
y'
\end{bmatrix}
$$
Para o moemnto de inercia tambem, conseguimos definir a matriz de rotação de um corpo rigido ao redor de um eixo arbitario. Por meio do Tensor do momento de inercia, dado por
$$
I_{\alpha \beta} = \int \rho \mathbf{r} \left(\delta_{\alpha \beta} - r_\alpha r_\beta \right) d^3r
$$
Onde $\rho \mathbf{r}$ é a densidade de massa e $\alpha, \beta$ são as componentes cartesianas e $\delta _{\alpha \beta}$ é o denta de Kronecker. O momento de inercia pode ser representado então pela matriz
$$
\mathbf{I} = 
\begin{bmatrix}
I_{xx} & I_{xy} & I_{xz} \\
I_{yx} & I_{yy} & I_{yz} \\
I_{zx} & I_{zy} & I_{zz}
\end{bmatrix}
$$
Pelo principio da simetria, onde $I_{xy} = I_{yx}$ é possivel achar uma rotação tal que os
componentes mistos são igual a zero e nos sobre apenas as componentes diagonais. Tal eixo é chamado de eixo principal e é dado por
$$
\mathbf{I}_p = 
\begin{bmatrix}
I_{xx} & 0 & 0 \\
0 & I_{yy} & 0 \\
0 & 0 & I_{zz}
\end{bmatrix}
$$


O primeiro dos grandes problemas que vamos enfrentar é resolver um sistema de n variaveis com n coeficientes. Em sua forma matricial, pode ser dado como
$$
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix}
=
\begin{bmatrix}
b_1 \\
b_2 \\
\vdots \\
b_n
\end{bmatrix}
$$
Onde podemos simplificar da forma $\mathbf{Ax = b}$. Vamos colocar que a matriz dos coeficientes, ou seja $\mathbf{A}$ seja não singular, ou seja, feita de linhas Linearmente Independentes. Vamos tentar resolver esse problema, que inicialmente parece facil. Para começo, vamos usar a matriz dos coeficientes aumentados, que junta as matrizes $\mathbf{A} \ e \ \mathbf{b}$, de forma:
$$
(\mathbf{A} | \mathbf{b}) =
\left[
\begin{array}{cccc|c}
a_{11} & a_{12} & \cdots & a_{1n}& b_1 \\
a_{21} & a_{22} & \cdots & a_{2n} & b_2 \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn} & b_n
\end{array}
\right]
$$

Outro problema que vamos atacar é a forma padrão de matrizes de autovalor, ou seja
$$
Av = \lambda v
$$
Onde é equivalente a escrever
$$
\begin{bmatrix}
A_{00} & A_{01} & \cdots & A_{0,n-1} \\
A_{10} & A_{11} & \cdots & A_{1,n-1} \\
\vdots & \vdots & \ddots & \vdots \\
A_{n-1,0} & A_{n-1,1} & \cdots & A_{n-1,n-1}
\end{bmatrix}
\begin{bmatrix}
v_0 \\
v_1 \\
\vdots \\
v_{n-1}
\end{bmatrix}
=
\lambda
\begin{bmatrix}
v_0 \\
v_1 \\
\vdots \\
v_{n-1}
\end{bmatrix}
$$
Onde $\lambda$ é o autovalor e $v$ é o autovetor. Uma forma de resolver nosso problema é mudar nossa
equação para
$$
(\mathbf{A} - \lambda \mathbf{I}) \mathbf{v} = \mathbf{0}
$$
Onde $\mathbf{I}$ é a matriz identidade. E $\mathbf{0}$ é uma matriz de zeros. Para uma solução não
trivial, vamos precisar que
$$
\det(\mathbf{A} - \lambda \mathbf{I}) = 0
$$
Ou seja, vamos precisar que a matriz $\mathbf{A} - \lambda \mathbf{I}$ seja singular. Expandindo
nosso determinante vamos ter nossa equação caracteristica, dada por
$$
(-1)^n \lambda^n + c_{n-1} \lambda^{n-1} + \cdots + c_1 \lambda + c_0 = 0
$$


Vamos introduzir o conceito de norma para uma matriz. Similar a como ja sabemos para um vetor, para
uma matriz sua formula é dada por:
$$
||\mathbf{A}|| = \sqrt{\sum_{i=0}^{n-1} \sum_{j=0}^{n-1} |A_{ij}|^2}
$$
Para vetores, por sua vez, sua norma é definida como
$$
||\mathbf{x}||_E = \sqrt{\sum_{i=0}^{n-1} |x_i|^2}
$$
Vamos agora derivar um criterio para que uma matriz sofra muito de pertubações pequenas, ou seja, quão perto de ser singular ela está. Começando com um problema não pertubado, vamos ter
$$
\mathbf{Ax} = \mathbf{b}
$$
Agora se adicionarmos uma pertubação pequena $\mathbf{\Delta A e \Delta x}$, vamos ter:
$$
\mathbf{A + \Delta A} \mathbf{x + \Delta x} = \mathbf{b}
$$
Onde mantemos nossa matriz $\mathbf{b}$ como constante
Expandindo nosso parenteses e substituindo $\mathbf{b}$, vamos ter
$$
\mathbf{A \Delta x} = -\mathbf{\Delta A}(\mathbf{x + \Delta x})
$$
Assumindo $\mathbf{A}$ como nao singular, vamos ter:
$$
\Delta x = -\mathbf{A}^{-1} \mathbf{\Delta A} \mathbf{x + \Delta x}
$$
Tomando a norma em ambos os lados
$$
||\Delta x|| = ||\mathbf{A}^{-1} \mathbf{\Delta A} \mathbf{x + \Delta x}|| \leq ||\mathbf{A}^{-1}||||\Delta \mathbf{A}||||\mathbf{x + \Delta x}||
$$
Usando certas propriedades, vamos ter
$$
\frac{||\Delta \mathbf{x}||}{||\mathbf{x + \Delta x}} \leq ||\mathbf{A}^{-1}||||\Delta \mathbf{A}||
$$
Dividindo e multiplicando por $\mathbf{A}$, vamos ter:
$$
\frac{||\Delta \mathbf{x}||}{||\mathbf{x + \Delta x}} \leq ||\mathbf{A}|| ||\mathbf{A}^{-1}||\frac{||\Delta \mathbf{A}||}{||\mathbf{A}||}
$$
Com isso, ela nos leva a acharmos o numero de condicionamento de uma matriz, que é dado por:
$$
\kappa(\mathbf{A}) = ||\mathbf{A}|| ||\mathbf{A}^{-1}||
$$
Um alto numero de condicionamento leva a uma matriz que vai sofrer muito por pequenas pertubações, enquanto uma menor sofre menos

Vamos agora, naturalmente extender para autovalores. Pulando a derivação,nosso criterio de condicionamento para autovalores é dado por:
$$
\kappa^{\lambda_i}_{ev}(\mathbf{A}) = \frac{1}{|\mathbf{u_i^T v_i}|}
$$


Vamos agora tentar resolver equacoes utilizando matrizes. Vamos iniciar para o caso mais simples, que sao para as matrizes triangulares. Matrizes triangulares sao aquelas que na diagonal principal, seja a acima ou abaixo, sao todas zero. Vamos comecar com o uma matriz triangular abaixo $\mathbf{L}$ de forma 
$$
\mathbf{Lx = b}
$$
Logo,
$$
\begin{pmatrix}
L_{00} & 0 & 0 \\
L_{10} & L{11} & 0 \\
L_{20} & L_{21} & L_{22}
\end{pmatrix}
\begin{pmatrix}
x_0 \\
x_1 \\
x_2
\end{pmatrix}
=
\begin{pmatrix}
b_0 \\
b_1 \\
b_2
\end{pmatrix}
$$
Onde pode ser expandida na forma
$$
\begin{align}
L_{00}x_0 &= b_0 \\
L_{10}x_0 + L_{11}x_1 &= b_1\\
L_{20}x_0 + L_{21}x_1 + L_{22}x_2 &= b_2
\end{align}
$$
Podemos derivar um formula geral

$$
x_i = \left(b_i - \sum_{j=0}^{i-1} L_{ij}x_j \right) \frac{1}{L_{ii}} , i= 0,1, ..., n-1
$$


Para uma matriz triangular acima $\mathbf{U}$, nossa derivacao é a mesma nos dando a formula
$$
x_i = \left( b_i - \sum_{j=0}^{i-1} U_{ij}x_j\right) \frac{1}{U_{ii}}, i = n-1, n-2, ..., 1, 0
$$
Vamos implementar

In [30]:
import numpy as np

def forsub(L, bs):
    """
    L: Matriz triangular superior
    bs: coeficientes
    """
    n = bs.size
    xs = np.zeros(n)
    for i in range(n):
        xs[i] = (bs[i] - L[i,:i] @xs[:i])/L[i,i] #o @ é o produto escalar, igual ao .cdot
    return xs

def backsub(U,bs):
    """
    U: matriz triangular inferior
    bs: coeficientes
    """
    n = bs.size
    xs = np.zeros(n)
    for i in reversed(range(n)):
        xs[i] = (bs[i] - U[i, i+1:]@xs[i+1:])/U[i,i]
    return xs

def testcreate(n,val):
    """
    n: tamanho da matriz
    val: valores iniciais
    """
    A = np.arange(val, val+n*n).reshape(n,n)
    A = np.sqrt(A)
    bs = (A[0,:])**2.1
    return A, bs

def testsolve(f, A, bs):
    """
    f: funcao de resolver
    A: Matriz
    bs: coeficientes
    """
    xs = f(A, bs); #print(xs)
    xs = np.linalg.solve(A, bs); #print(xs)
    
A, bs = testcreate(4,21)
L = np.tril(A)
testsolve(forsub, L, bs)
print(" ")
U = np.triu(A)
testsolve(backsub, U, bs)

Vamos nos virar agora para o processo de resolver qualquer equacao linear sem a necessidade de nossa matriz ser triangular.Uma das principais maneiras que fazemos isso é por meio da eliminacao gaussiana. A ideia principal é fazermos a eliminacao de termos ate que tenhamos uma matriz triangular superior. Para isso, vamos utilizar do processo de mesclar a matriz $\mathbf{A}$ com $\mathbf{B}$. Para um caso geral, com uma matriz $n \times n$. Inicialmente, dado um passo intermediario, nossa matriz pode ser parecer com
$$ %Terminar na ia
\left[
\begin{array}{ccccccccc|c}
A_{00} & A_{01} & A_{02} & \dots & A_{0,j-1} & A_{0, j} & A_{0,j-1} & \dots & A_{0,n-1} & b_0 \\
0 & A_{11} & A_{12} & \dots & A_{1,j-1} & A_{1, j} & A_{1,j-1} & \dots & A_{1,n-1} & b_1 \\
0 & 0 & A_{22} & \dots & A_{2,j-1} & A_{2, j} & A_{2,j-1} & \dots & A_{2,n-1} & b_2 \\
\vdots & \vdots & \vdots & \ddots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots\\
0 & 0 & 0 & \dots & A_{j-1,j-1} & A_{j-1, j} & A_{j-1,j-1} & \dots & A_{j-1,n-1} & b_{j-1} \\
0 & 0 & 0 & \dots & A_{jj} & A_{jj+1} & A_{j,j+2} & \dots & A_{j,n-1} & b_j\\
\vdots & \vdots & \vdots & \ddots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots\\
0 & 0 & 0 & \dots & A_{ij} & A_{ij+1} & A_{i,j+2} & \dots & A_{i,n-1} & b_i \\
\vdots & \vdots & \vdots & \ddots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots\\
0 & 0 & 0 & \dots & A_{n-1,j} & A_{n,j} & A_{n-1,j+1} & \dots & A_{n-1,n-1} & b_{n-1}
\end{array}
\right]
$$
Onde a linha $j$ virou a linha de pivo, onde todas as linhas antes dela ja foram modificadas, menos a primeira que me mantem igual, e depois dela nenhuma foi modificada, logo $j$ pode variar de
$$
j = 1, 2, 3 , \dots, n-2
$$
Se denotarmos como $i$ linha que esta sendo modificada, seu valor pode variar de
$$
i = j+1, j+2, \dots, n-1
$$
Para a eliminacao, multiplicamos a linha  pivo $j$ por um coeficiente e subtraimos da linha $i$. O coeficiente é escolhido de forma que $i$ comece com 0. Esse coeficiente é escolhido pela equacao
$$
coef = \frac{A_{ij}}{A_{jj}}
$$
Vamos implementar

In [31]:
def gausselim(inA, inbs):
    A = np.copy(inA)
    bs = np.copy(inbs)
    n = bs.size
    
    for j in range(n-1):
        for i in range(j+1, n):
            coeff = A[i,j] / A[j,j]
            A[i,j:] -= coeff*A[j,j:]
            bs[i] -= coeff*bs[j]
    xs = backsub(A,bs)
    return xs
A, bs = testcreate(4,5)
testsolve(gausselim, A, bs)


Esse metodo é bastante robusto ate, mas temos aluns problemas. Se tivermos a  mesma matriz $\mathbf{A}$ mas uma diferente de $\mathbf{b}$, toda nossa eliminacao foi jogada fora, pois teriamos que chamar denovonossa funcao. Um metodo que resolve isso é metodo LU. Esse metodo vem de varios sabores,mas vamos pegar o mais simples que é por meio de uma decomposicao da nossa matriz $\mathbf{A}$ em $\mathbf{LU}$, ou seja, uma triangular inferiore superior. Vamos assumir um item a mais. Nossa matriz $\mathbf{L}$ é uma matriz inferior unitaria, ou seja,sua diagonal principal contem apenas $1$. Para resolver, vamos descrever nosso sistema como
$$
\begin{align}
\mathbf{Ax = b}\\
\mathbf{LUx = b}\\
\mathbf{L (Ux) = b}\\
\mathbf{Ly = b}\\
\mathbf{Ux = y}
\end{align}
$$
Vamos implentar

In [32]:
def lu_decom(A):
    """
    A: matriz a ser decomposta
    Devolve L, U
    """
    n = A.shape[0]
    U = np.copy(A)
    L= np.identity(n)
    
    for  j in range(n-1):
        for i in range(j+1, n):
            coeff = U[i,j] / U[j,j]
            U[i,j:] -= coeff*U[j,j:]
            L[i,j] = coeff
    return L, U

def lu_solve(A, bs):
    """
    A: matriz para resolver
    bs: matriz dos coeficientes
    """
    L, U = lu_decom(A)
    
    ys = forsub(L, bs)
    xs = backsub(U, ys)
    return xs

A, bs = testcreate(4,21)
testsolve(lu_solve,A,bs)

Inversoes de matrizes tambemm sao uma forma de resolvermos. Porem é interessante evitar esse metodo, pelo fato de ser computacionalmente caro. Mas de qualquer jeito é interessante saber. Inicialmente, lembramos do fato
$$
\mathbf{\mathcal{I} = AA^{-1}}
$$
Se pensarmos de $\mathcal{I}$ como conposta de varios vetores colunas $e_i$, podemos quebrar nosso problema como $n$ problemas da forma
$$
\mathbf{Ax_i = e_i}
$$
Onde 
$$
\mathbf{A}^{-1} = 
\begin{pmatrix}
\mathbf{x_0} & \mathbf{x_1} & \dots & \mathbf{x_{n-1}} \\
\end{pmatrix}
$$
Utilizando o metodo anterior, podemos  reescrever como
$$
\mathbf{L(Ux_i) = e_i}
$$
esse metodo funciona, mas é computacionalmente muito caro, entao nao utilizamos



Vamos lembrar do determinante. Para uma matriz triangular, seu determinantes é apenas o produto da sua diagoal, logo
$$
\det (\mathbf{A}) = \det (\mathbf{L}) + \det (\mathbf{U}) = \left( \Pi_{i=0}^{n-1} 1 \right) \cdot \left( \Pi_{i=0}^{n-1} U_{ii}\right) = \Pi_{i=0}^{n-i} U_{ii}
$$

Podemos resolver alguns problemas do nosso metodo,principalmente se tivermos numeros muito,muito pequenos ou zero como pivo.Para remediar podemos aplicar
$$
|A_{kj} = \max_{j \geq m \geq n-1} |A_{mj}|
$$
Onde inves de so pegarmos $A_{jj}$ cegamente, buscamos pelo maior valor e usamos ele. Vamos implementar:

In [33]:
def gauss_elim_pivot(inA, inbs):
    """
    A: matriz que queremos a solucao
    b: matriz dos coeficientes
    """
    A = np.copy(inA)
    bs = np.copy(inbs)
    n = bs.size
    
    for j in range(n-1):
            k = np.argmax(np.abs(A[j:,j])) + j
            if k != j:
                A[j,:], A[k,:] = A[k,:], A[j,:].copy()
                bs[j] , bs[k] =  bs[k], bs[j]
            
            for i in range(j+1, n):
                coeff = A[i,j] / A[j,j]
                A[i,j:] -=coeff*A[j,j:]
                bs[i] -= coeff*bs[j]
    
    xs = backsub(A,bs)
    return xs

A, bs = testcreate(3,27)
testsolve(gauss_elim_pivot, A, bs)

Alem desse metodo, que é um metodo,digamos, fechados e diretos, temos metodoso mais interativos, ou seja, aqueles que dinamicamente vao refinando nossa solucao. Um desses que vamos estudar é o metodo iterativo de Jacabi. Nele vamos iniciar com um chute $\mathbf{x}$ e vamos refinando-a pouco a pouco, com cada iteracao, ate um valor desejado. Com isso, nao é surpreso que eles, geralmente, demoram mais e podem ate nao convergir.
Mas vamos pensar, qual a vantagem dele entao se nao da uma solucao exata e demora mais? eles sao mais eficientes na questao computacional e para matrizes dispersas, onde a maioria de seus termos sao $0$, eles sao mais eficientes. Esse metodo é talvez o mais simples e posteriormente veremos outros mais refinados.

Vamos ver seu algoritmo. Reescrevendo nossa equacao por meio de indices
$$
\sum_{j=0}^{n-1} A_{ij}x_j = b_i, i=0, 1, 2, \dots, n-1
$$
O metodo de jacobi pega essa equacao e tenta resolver para o elemento $x_i$, que corresponde ao elemento da diagonal $A_{ii}$, de forma
$$
x_i = \left(b_i - \sum_{j=0}^{i-1} A_ijx_j - \sum_{j = i+1}^{n-1}\right) \frac{1}{A_{ii}}, i=0, 1, 2, \dots, n-1
$$
O metodo comeca chutando um vetor $\mathbf{x^{(0)}}$ e estimamos o vetor $\mathbf{x^{(1)}}$ pela formula
$$
x_i^{(1)} = \left(b_i - \sum_{j-0}^{i-1}A_ijx_j^{(0)} - \sum_{j=i+1}^{n-1} A_ijx_j^{(0)}\right) \frac{1}{A_{ii}}, i = 0, 1, 2, \dots, n-1
$$
E assim podemos seguir na nossa iteracao ate quando precisarmos. Nossa forma de iteracao se da
$$
x_i^{(k)} = \left(b_i - \sum_{j=0}^{i-1}A_{ij}x_j^{(k-1)} - \sum_{j=i+1}^{n-1}A_{ij}x_j^{(k-1)}\right) \frac{1}{A_{ii}}, i=0, 1, 2, \dots, n-1
$$
O chute inicial pode ser arbitrario, talvez uma matriz nula ou apenas com 1. Mas independete do chute a depender da matriz ela nao pode convergir, sendo necessario que elas sejam diagonalmente dominantes. Nem todas sao, mas podem ser rearranjadas para virar. Vamos implementar

In [34]:
def termcrit(xolds,xnews):
    """
    Funcao que vai calcular um erro maximo que vamos aceitar para nossa iteracao
    xold: vetor com a iteracao passada
    xnew: novo x depois da iteracao
    """
    errs = np.abs((xnews-xolds)/xnews)
    return np.sum(errs)

def jacobi(A, bs, kmax=50, tol=1.e-6):
    """
    Implementacao da nossa interacao de Jacobi
    A: matriz inicial que queremos resolver.
    bs: matriz de coeficientes
    kmax: numero de iteracoes
    tol: tolerancia que vamos aceitar
    """
    n = bs.size
    xnews = np.zeros(n)
    
    for k in range(1, kmax):
        xs = np.copy(xnews)
        for i in range(n):
            slt = A[i,:i]@xs[:i]
            sgt = A[i, i+1:]@xs[i+1:]
            xnews[i] = (bs[i] - slt - sgt) / A[i,i]
        
        err = termcrit(xs, xnews)
        #print("it:{}, novo_x:{}, erro:{}".format(k, xnews, err))
        if err < tol:
            break
    else:
        xnews = None
    return xnews

n = 4; val = 27
A, bs = testcreate(n, val)
A += val*np.identity(n)
testsolve(jacobi, A, bs)

Vamos agora para a segunda parte bruta da algebra linear, que são resolver problemas com autovalores. Lembramos que nossa equação se da
$$
\mathbf{Av_i = \lambda v_i}
$$
Vamos supor que nossa matriz $n \times n$ possui $n$ autovalores distintos. Se isso for verdade, podemos escrever a seguinte relação
$$
\mathbf{V^{-1}AV = \Lambda}
$$
Onde $\mathbf{\Lambda}$ é a matriz diagonal com os autovalores na $\lambda_i$ nas suas diagonais.
$$
\mathbf{\Lambda} =
\begin{pmatrix}
\lambda_0 & 0 & \dots & 0 \\
0 & \lambda_1 & \dots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \dots & \lambda_{n-1}
\end{pmatrix}
$$
Onde $\mathbf{V}$ é a matriz de vetores colunas que sao os autovetores
$$
\mathbf{V} =
\begin{pmatrix}
\mathbf{v_0} & \mathbf{v_1} & \dots & \mathbf{v_{n-1}} \\
\end{pmatrix}
$$



Vamos começar a atacar nosso problema. Inicialmente, vamos pegar o método mais facil, que é o metodo da potencia. Nele, ele so nos da 1 par autovetor-autovalor. Como cada autovalor é distinto podemos organiza-los de forma
$$
|\lambda_0| > |\lambda_1| > \dots > |\lambda_{n-1}|
$$
O metodo da potencia consiste em pegar um chute inicial $\mathbf{z^{(0)}}$ e multiplicar pela matro\ $\mathbf{A}$ para obtermos a proxima iteracao. Pela formula de chutes, vamos ter
$$
\mathbf{z^{(k)} = A^kz^{(0)}} \quad k=1, 2, 3, \dots
$$
Onde podemos expressar nossa matriz $\mathbf{z^{(0)}}$ como uma combinação linear dos nossos autovetores, da forma
$$
\mathbf{z^{(0)}} = \sum_{i=0}^{n-1} c_i \mathbf{v_i}
$$
Onde $c_i$ sao os coeficientes da combinação linear, estes, desconhecidos. Substituindo na nossa formula de iteracao
$$
\mathbf{z^{(k)} = A^kz^{(0)}} = \sum_{i=0}^{n-1} c_i A^k \mathbf{v_i} = \sum_{i=0}^{n-1} c_i \lambda^k \mathbf{v_i} = c_0 + \lambda_0^k \mathbf{v_0} + \lambda_0^k \sum_{i=1}^{n-1}c_i \left(\frac{\lambda_i}{\lambda_0}\right)^k \mathbf{v_i} \quad k=1, 2, 3, \dots
$$
Como forma de podermos avaliar essa expressão, vamos introduzir o quociente de Rayleigh dado como
$$
\mu (\mathbf{x}) = \frac{\mathbf{x^TAx}}{\mathbf{x^Tx}}
$$
Se $\mathbf{x}$ for um autovetor, temos que $\mu(\mathbf{x}) = \lambda$. Se $\mathbf{x}$ nao for um autovetor, temos que $\mu(\mathbf{x}) \approx \lambda$. Como mais um passo, vamos introduzir o vetor $\mathbf{q^{(k)}}$ que tem a propriedade de sua norma valer $1$, ou seja, ele é a normalização do vetor $\mathbf{z^{(k)}}$.
$$
\mathbf{q^{(k)}} = \frac{\mathbf{z^{(k)}}}{||\mathbf{z^{(k)}}||}
$$
Logo, nosso quociente de Rayleigh pode ser escrito como
$$
\mu(\mathbf{q^{(k)}}) = [\mathbf{q}^{(k)}]^T\mathbf{Aq^{(k)}}
$$
Logo, nosso algoritmo pode ser escrito como essa sequencia de passos
$$
\begin{align}
\mathbf{z^{(k)}} &= \mathbf{Aq^{(k-1)}} \\
\mathbf{q^{(k)}} &= \frac{\mathbf{z^{(k)}}}{||\mathbf{z^{(k)}}||} \\
\mu(\mathbf{q^{(k)}}) &= [\mathbf{q^{(k)}}]^T\mathbf{Aq^{(k)}}
\end{align}
$$
Vamos implementar

In [35]:
def magnitude(xs):
    """Calcula a magnitude do nosso vetor

    Args:
        xs (array): nosso vetor a qual queremos calcular a magnitude
    """
    return np.sqrt(np.sum(xs*xs))
def power(A, kmax=6):
    """Implementa o algoritimo de potencia

    Args:
        A (Array): Matriz no qual queremos saber os autovetores e valores
        kmax (int, optional): Numero maximo de k. Defaults to 6.
    """
    zs = np.ones(A.shape[0])
    qs = zs / magnitude(zs)
    for k in range(1, kmax):
        zs = A@qs
        qs = zs/magnitude(zs)
        #print(k, qs)
    lam = qs@A@qs
    return lam, qs

def testeigone(f, A, indx=0):
    """Vai testar se conseguimos achar nosss autovalores e vetores

    Args:
        f (Funcao): Funcao que vamos comparar para ver se acertamos
        A (Array): Matriz em que vamos achar nosso autovalores e autovetores
        indx (int, optional): Index do nosso autovalor e vetor. Defaults to 0.
    """
    eigval, eigvec = f(A)
    #print(" "); print(eigval); print(eigvec)
    npeigvals, npeignvecs = np.linalg.eig(A)
    #print(" ")
    #print(npeigvals[indx]); print(npeignvecs[:,indx])

A, bs = testcreate(4, 21)     
testeigone(power,A)   

Agora vamos usar uma variação do método da potencia, que nos permitira calcular o autovetor de menor magnitude, inves do de menor. Para isso, vamos usar o metodo da potencia inversa. Ele é muito parecido com o metodo da potencia, mas ao inves de multiplicar pela matriz $\mathbf{A}$, vamos multiplicar pela matriz inversa $\mathbf{A^{-1}}$. A formula de iteracao se da
$$
\mathbf{Az^{(k)} = q^{(k-1)}} \quad k=1, 2, 3, \dots
\mathbf{q^{(k)}} = \frac{\mathbf{z^{(k)}}}{||\mathbf{z^{(k)}}||}
\mu (\mathbf{q^{(k)}}) = [\mathbf{q^{(k)}}]^T\mathbf{q^{(k)}}
$$
Vamos refinar um pouco esse método. Voltando a definir nossa equação como $\mathbf{Av_i = \lambda_i v_i}$, subtrair ambos os lados por $s\mathbf{v_i}$, onde $s$ é um escalar arbitrario, logo nossa equação se da:
$$
\mathbf{(A - s\mathcal{I})v_i} = \mathbf{(\lambda_i - s) v_i}
$$
Onde pode ser escrita como
$$
\begin{align}
\mathbf{A^{\star} v_i} &= \mathbf{\lambda_i^{\star} v_i} \\
\mathbf{A^{\star}} &= \mathbf{A - s\mathcal{I}} \\
\mathbf{\lambda_i^{\star}} &= \mathbf{\lambda_i - s}
\end{align}
$$
Aplicando o nosso metodo da potencia inversa, teremos:
$$
\begin{align}
\mathbf{A^{\star}z} &= \mathbf{q^{(k-1)}} \\
\mathbf{q^{(k)}} &= \frac{\mathbf{z^{(k)}}}{||\mathbf{z^{(k)}}||} \\
\mu (\mathbf{q^{(k)}}) &= [\mathbf{q^{(k)}}]^T\mathbf{q^{(k)}}
\end{align}
$$
Onde vamos achar o melhor autovalor mais perto de $s$
Vamos implementar

In [36]:
def power_shift_inv(A, s=20, kmax=200, tol=1e-8):
    """
    A: Matriz que queremos saber menor autovalor
    s: valor que vamos dar o shift
    kmax: numero maximo de iteracoes
    tol: tolerancia
    """
    n = A.shape[0]
    znews = np.ones(A.shape[0])
    qnews = znews / magnitude(znews)
    A_star = A - np.identity(A.shape[0])*s
    L, U = lu_decom(A_star)
    for k in range(1, kmax):
        qs = np.copy(qnews)
        ys = forsub(L, qs)
        znews = backsub(U, ys)
        qnews = znews / magnitude(znews)
        
        if qs@qnews < 0:
            qnews = -qnews
            
        err = termcrit(qs, qnews)
        #print(k, qnews, err)
        
        if err < tol:
            lam = qnews@A@qnews
            break
    else:
        lam = qnews = None
    return lam, qnews

A, bs = testcreate(4,21)
testeigone(power_shift_inv,A)

Agora vamos ver outro metodo, chamado decomposicao QR. tal metodo se baseia em decompor nossa matriz em uma diagonal $\mathbf{Q}$ e outra triangular superior $\mathbf{R}$, de forma
$$
\mathbf{A = QR}
$$
Sendo esse um metodo direto, diferente dos outros que ja vimos. Pulando a parte da demonstracao, para construirmos nossa matrz ortogonal, com vetores colunas $\mathbf{q_j}$, vamos fazer
$$
\begin{align}
\mathbf{a_j ^\prime} &= \mathbf{a_j} - \sum_{i=0}^{j-1} \mathbf{(q_i^Ta_j)q_i} \\
\mathbf{q_j} &= \frac{\mathbf{a_j^\prime}}{||\mathbf{a_j^\prime}||}
\end{align}
$$
Para a matriz $\mathbf{R}$, construimos de forma
$$
R_{ij} = \mathbf{q_i^Ta_j} \quad j=0,1,\dots,n-1, \ i=0,1,\dots, j-1 \\
R_{jj} = ||\mathbf{a_j^\prime}|| = ||\mathbf{a_j} - \sum_{i=0}^{j-1}R_{ij}\mathbf{q_i}|| \quad j=0,1,\dots,n-1
$$
Vamos implementar

In [37]:
def qrdecomposition(A):
    """
    Funcao que faz a nossa decomposicao QR
    A: Matriz que vamos decompor
    """
    n = A.shape[0]
    Ap = np.copy(A)
    Q = np.zeros((n,n))
    R = np.zeros((n,n))
    
    for j in range(n):
        for i in range(j):
            R[i,j] = Q[:,i] @ A[:,j]
            Ap[:,j] -= R[i,j] * Q[:,i]
        R[j,j] = magnitude(Ap[:,j])
        Q[:,j] = Ap[:,j] / R[j,j]
    return Q,R
def testqrdecomposition(A):
    """
    vamos testar se nossa decomposicao deu certo ou nao
    A: Matriz a ser decomposta
    """
    n = A.shape[0]
    Q, R = qrdecomposition(A)
    
    diff_a = A - Q@R
    diff_q = Q.T@Q - np.identity(n)
    #print(n,magnitude(diff_a), magnitude(diff_q))
for n in range(4,10,2):
    A, bs = testcreate(n,21)
    testqrdecomposition(A)

Esse metodo nos serve bem na questao de nos dar uma boa aproximacao para a matriz $\mathbf{A}$. Porem, para a matriz $\mathbf{Q}$, ela nos da uma diferenca muito grande, que chega a ser ate um pouco triste. Vamos introduzir rapidamente o conceito de transformações similares. Dado uma matrzi $\mathbf{A}$, podemos encontrar uma matriz $\mathbf{S}$ tal que
$$
\mathbf{A^\prime = S^{-1}AS}
$$
Onde assumimos apenas que $\mathbf{S}$ seja invertivel. Com isso, conseguimos demonstrar que
$$
\mathbf{A^\prime S^{-1}v_i} = \lambda_i \mathbf{S^{-1}v_i}
$$
Onde podemos definir que
$$
\begin{align}
v_i^\prime &= \mathbf{S^{-1}v_i}
\mathbf{A^\prime v_i^prime} &= \lambda_i \mathbf{v_i^prime}
\end{align}
$$
Portanto, descobrimos que duas matrizes similares possuem os mesmos autovalores, mas nao necessariamente os mesmos autovetores. Ademais, caso $\mathbf{S}$ seja uma matriz ortogonal, podemos dizer que, relembrando que definimos $\mathbf{Q}$
$$
\mathbf{A^\prime = Q^T A Q}
$$


Vamos agora discutir um pouco sobre o método de iterações simultâneas. Esse método é a generalização do método das potencias para mais de 1 autovetor. Começando, vamos assumir que todos os autovalores são distintos. Anteriormente, nos começamos com um chute para esse autovalor, mas agora, vamos fazer $n$ chutes numa tentativa de acharmos todos. Logo, nosso vetor inicial se da na forma
$$
\mathbf{Z^{(0)}} = \begin{bmatrix}
\mathbf{z_0^{(0)}} & \mathbf{z_1^{(0)}} & \dots & \mathbf{z_{n-1}^{(0)}}
\end{bmatrix}
$$
Uma forma de fazermos isso, é colocar que nosso vetor $\mathbf{Z^{(0)}}$ é uma matriz identidade $n \times n$ de forma
$$
\mathcal{\mathbf{I}} = \begin{bmatrix}
\mathbf{e_0} & \mathbf{e_1} & \dots & \mathbf{e_{n-1}}
\end{bmatrix}
$$
As nossas próximas matrizes vão se dar na forma
$$
\mathbf{Z^{(k)}} = \mathbf{AZ^{(k-1)}} \quad k=1,2,3,\dots
$$
Um nosso vetor $\mathbf{z_j^{(k)}}$ se da como
$$
\mathbf{z_j^{(k)}} = \sum_{i=0}^{n-1} c_{ij}\lambda _i^{(k)}\mathbf{v_i}
$$
Precisamos tomar cuidado, que para cada iteração, vamos precisar fazer uma ortonomalização. Portando, nossos passos ficam da forma
$$
\begin{align}
\mathbf{Z^{(k)}} &= \mathbf{A}\mathbf{\mathbb{Q}^{(k-1)}}\\
\mathbf{Z^{(k)}} &= \mathbf{\mathbb{Q}^{(k)}}\mathbf{\mathbb{R}^{(k)}}\\
\end{align}
$$
Onde, $\mathbf{\mathbb{Q}^{(0)}} = \mathcal{\mathbf{I}}$ Podemos definir $\mathbf{\mathbb{R}^{(k)}}$ como o produto em ordem reversa de $\mathbf{R^{(i)}}$, logo
$$
\mathbf{\mathbb{R}^{(k)}} = \mathbf{R^{(k)}}\mathbf{R^{(k-1)}}\dots\mathbf{R^{(1)}}
$$
Portando, disso, pode-se definir que
$$
\mathbf{A}^k = \mathbf{\mathbb{Q}^{(k)}}\mathbf{\mathbb{R}^{(k)}}
$$
Para uma matriz $\mathbf{A}$, que é simétrica, essa decomposição nos leva aos autovetores, já para uma matriz $\mathbf{A}$ que não é simétrica, essa decomposição faz com que $\mathbf{\mathbb{Q}^{(k)}}$ convejerá para o "fator ortogonal" dos autovetores, ou seja, para a matriz $\mathbf{\tilde{Q}}$ em $\mathbf{V = \tilde{Q}U}$, onde $\mathbf{U}$ é uma matriz triangular superior. De qualquer forma $\mathbf{\mathbb{Q}^{(k)}}$ esta relacionado com os autovetores de $\mathbf{A}$.
Para extrairmos os autovetores, vamos primeiro generalizar o quociente de Rayleigh, para a forma
$$
\mathbf{A^{(k)}} = [\mathbf{\mathbb{Q}}^{(k)}]^T\mathbf{A}\mathbf{\mathbb{Q}^{(k)}}
$$
Portanto, para o método final, vamos ter 
$$
\begin{align}
\mathbf{A^{k}} &= [\mathbf{\mathbb{Q}^{(k)}}]\mathbf{\mathbb{R}^{(k)}}\\
\mathbf{A^{(k)}} &= [\mathbf{\mathbb{Q}^{(k)}}]^T\mathbf{A}\mathbf{\mathbb{Q}^{(k)}}\\
\end{align}
$$


Com tudo isso em mente, conseguimos agora definir o algoritmo QR. Ele é muito similar ao das iterações simultâneas, em fato é equivalente. Seus passos, muito simples, são dados por
$$
\begin{align}
\mathbf{A^{(k-1)}} &= \mathbf{Q^{(k)}}\mathbf{R^{(k)}}\\
\mathbf{A^{(k)}} &= \mathbf{R^{(k)}}\mathbf{Q^{(k)}}\\
\end{align}
$$
Onde nossa matriz $\mathbf{A^{(0)}} = \mathbf{A}$. Olhe que interessantemente, para produzirmos nossa próxima matriz, apenas multiplicamos a nossa da decomposição anterior em ordem reversa. Então, temos que inicialmente decompor nossa matriz $\mathbf{A}$ em uma $\mathbf{QR}$, multiplicar em ordem inversa, decompor a proxima e seguir assim. Vamos implementar

In [38]:
def qrmetod(inA, kmax=100):
    """Implementa o método de solução QR

    Args:
        inA (Array): Matriz A que queremos os autovalores e vetores
        kmax (int, optional): Numero maximo de iterações que vamos fazer. Defaults to 100.
    """
    A = np.copy(inA)
    for k in range(1, kmax):
        Q, R = qrdecomposition(A)
        A = R@Q
        #print(k, np.diag(A))
    qreigvals = np.diag(A)
    return qreigvals

A, bs = testcreate(4,21)
qreignval = qrmetod(A, 6)
print(" ")
npeignvals, npeignvecs = np.linalg.eig(A); print(npeignvals)    

 
[ 2.13166627e+01 -6.72337148e-02 -6.93022639e-05 -7.50128339e-08]


Caso queiramos melhorar nosso método, fazendo-o computacionalmente menos caro, podemos fazer um pre-processamento da nossa matriz $\mathbf{A}$, usando a forma de Hessenberg.

Agora que ja temos uma boa estimativa para os autovalores, podemos construir uma boa estimativa para os autovetores. Para isso, vamos usar o método das potencias inversas. Tendo já em mãos os autovalores, esse método converge bastante rápido para os autovetores. O que fazemos foi avaliar nossos autovalores e iterar 1 a 1 pelo método das potencias inversas, nos dando então nosso autovetor. Vamos implementar

In [41]:
def eig(A, eps=1e-12):
    """Faz o nosso pré processamento e nos acha nossos auto valores e vetores

    Args:
        A (Array): Matriz A que queremos os autovalores e vetores
        eps (float, optional): erro maximo permitido. Defaults to 1e-12.
    """  
    n = A.shape[0]
    eigvals = np.zeros(n)
    eigvecs = np.zeros((n,n))
    qreignvals = qrmetod(A)
    for i, qre in enumerate(qreignvals):
        eigvals[i], eigvecs[:,i] = power_shift_inv(A, qre+eps) 
    return eigvals, eigvecs
def testeigall(f, A):
    """Vai testar se conseguimos achar nosss autovalores e vetores

    Args:
        f (Funcao): Funcao que vamos comparar para ver se acertamos
        A (Array): Matriz em que vamos achar nosso autovalores e autovetores
    """
    eigvals, eigvecs = f(A)
    npeigvals, npeignvecs = np.linalg.eig(A)
    print(eigvals); print(npeigvals)
    print(" ")
    for eigvecs, npeignvecs in zip(eigvecs.T, npeignvecs.T):
        pass
        print(eigvecs); print(npeignvecs)
        print(" ")

A, bs = testcreate(3, 27)
testeigall(eig, A)

[ 1.66974766e+01 -1.74754610e-02 -4.56998776e-06]
[ 1.66974766e+01 -1.74754610e-02 -4.56998776e-06]
 
[0.54872345 0.57735058 0.60462293]
[-0.54872345 -0.57735058 -0.60462293]
 
[ 0.72582037 -0.0152504  -0.68771522]
[-0.72582037  0.0152504   0.68771522]
 
[-0.40155006  0.81649635 -0.41483883]
[ 0.40155006 -0.81649635  0.41483883]
 
